### ISSUE TITLE
can not run properly with display error

### ISSUE THREAD

**Issue by waynezw0618** [jerabaul29/Cylinder2DFlowControlDRL#7]
Dear SIr
 I am using your singularity image to run some simulation. But I get problem with running even single_runer case with followling error, can you please help me to fix that?

vagrant@vagrant:/vagrant/Cylinder2DFlowControlDRL/Cylinder2DFlowControlWithRL/baseline_flow$ python single_runner.py 
--------------------------------------------------------------------------
[[52445,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: vagrant

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
iUFL can be obtained from https://github.com/MiroK/ufl-interpreter
resume env
    --- call init ---
          mesh_file = mesh/turek_2d.h5
-0.2 0.21
          total_number_of_probes = 151
    --- done init ---
define network specs
define agent
  environment.states = {'shape': (151,), 'type': 'float'}
  environment.actions = {'max_value': 0.01, 'shape': (2,), 'min_value': -0.01, 'type': 'float'}
  network_spec = [{'type': 'dense', 'size': 512}, {'type': 'dense', 'size': 512}]
2019-06-15 00:57:31.474054: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-06-15 00:57:31.508053: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2019-06-15 00:57:31.508848: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:145] kernel driver does not appear to be running on this host (vagrant): /proc/driver/nvidia/version does not exist
Trained Network not found...
  start simulation
2019-06-15 00:57:32.020531: W tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc:1441] Failed to build SimpleGraphView.
2019-06-15 00:57:32.022051: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:586] Iteration = 0, topological sort failed with message: Non-existent input ^ConstantFoldingCtrl/ppo/cond/add/Switch_0 for node ConstantFolding/ppo/cond/strided_slice_1/stack_const_axis
2019-06-15 00:57:32.022916: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:586] Iteration = 1, topological sort failed with message: Non-existent input ^ConstantFoldingCtrl/ppo/cond/add/Switch_0 for node ConstantFolding/ppo/cond/strided_slice_1/stack_const_axis
Traceback (most recent call last):
  File "single_runner.py", line 150, in <module>
    one_run()
  File "single_runner.py", line 119, in one_run
    state, terminal, reward = environment.execute(null_action)
  File "/vagrant/Cylinder2DFlowControlDRL/Cylinder2DFlowControlWithRL/baseline_flow/../Env2DCylinder.py", line 799, in execute
    self.visual_inspection()
  File "/vagrant/Cylinder2DFlowControlDRL/Cylinder2DFlowControlWithRL/baseline_flow/../Env2DCylinder.py", line 461, in visual_inspection
    plt.subplots(total_number_subplots, 1)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 1177, in subplots
    fig = figure(**fig_kw)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0.0"
Aborted (core dumped)

**Comment by jerabaul29** [comment]
This is not really related to the code itself, but rather to the fact that your host is Mac. Mac does things its own ways, which breaks the display export. I only have access to Ubuntu systems and I do not plan on debugging for Mac oddities. My recommendations:

- try to export on a different display: see https://unix.stackexchange.com/questions/85782/error-no-protocol-specified-when-running-from-remote-machine-via-ssh/295863#295863 the recommendation ```export DISPLAY=:10```

- maybe shifting matplotlib render engine may help.

- if it does not help, take away the display export and disable the plotting flags.

- best solution would be to run using a Ubuntu or other standard Linux distro running singularity not vagrant. Anyways all this ML / AI stuff is developed with focus for Linux hosts, so many things break all the time with Mac / Windows.

Good luck.

**Comment by waynezw0618** [comment]
Thanks a lot! seems it is the problem of Mac.

**Comment by jerabaul29** [comment]
Ok, is it working now? :)

**Comment by jerabaul29** [comment]
No answer, so I guess this is working, closing now.

**Comment by waynezw0618** [comment]
Sorry for late reply. it doesn't work for my MacBook. looking for the way to solve it :(

**Comment by jerabaul29** [comment]
@jviquerat had you found a way to get the display to work with vagrant on Mac? :)

**Comment by waynezw0618** [comment]
No, any suggestion?

**Comment by waynezw0618** [comment]
I am trying to install singularity directly on my MacBook, since there is an alpha version. there are following errors:
 python single_runner.py 
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
[(none):01109] opal_ifinit: unable to find network interfaces.
[(none):01109] mca: base: components_open: component if / posix_ipv4 open function failed
[(none):01109] oob_tcp: problems getting address for index 65861792 (kernel index -1)
--------------------------------------------------------------------------
No network interfaces were found for out-of-band communications. We require
at least one available network for out-of-band messaging.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_oob_base_select failed
  --> Returned value (null) (-43) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[(none):1109] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!

**Comment by jerabaul29** [comment]
This is purely an IT question and not really related to the code. I do not have myself access to a Mac, so I am afraid that you will have to sort it out yourself and I cannot really help. I recommend that you find a Linux machine (virtalbox on your mac / dual boot on your mac / Amazon Web Service of similar / a machine at your university / some other option). If not you may try to comment out the matplotlib stuff, as this probably is purely due to matplotlib and mac oddities.

**Comment by waynezw0618** [comment]
：） ok，I am working on this..

**Comment by waynezw0618** [comment]
I actually tried installed a virtual box and ubuntu there. then the error goes to the apt-get... 
I appreciate if you can upload docker images, which I am familiar with.. thanks!

**Comment by jerabaul29** [comment]
I am sorry, on this specific project the container was built by the IT department and I only have access to a singularity image.

If you want to contribute, it would be very nice to create a working docker image. This may be relatively little work if you are familiar with docker and command line installs, as you can simply open the singularity, check the version of all the packages in command line, and install the corresponding packages in the same version in docker.

If you do so, may you consider doing a push request with the docker image as a .tar file? If you do so I will be happy to add an 'acknowledgement' section or something in this kind.

**Comment by waynezw0618** [comment]
I'd like to make contribution. but first of all I need to make it works at least on my laptop

**Comment by waynezw0618** [comment]
still struggling with conflicts between this and that ... 
Seem you are using python2.7?

**Comment by jerabaul29** [comment]
Yes, this is based on the tensorforce from 2018, which was python 2.7 .

**Comment by waynezw0618** [comment]
Still I haven't manage to install both. many conflicts. 
I actually pulled a fresh ubuntu image, and install everything from Anaconda. Since Fenics is not easy to build manually from source. I follow the installation document in feniceproject website get everything for python3( conda, docker, ). now i enforce installing python=2.7 and tensorflow=1.8.0 then conflicts goes to the gcc 4.8.5, see here:https://github.com/conda-forge/fenics-feedstock/issues/89

I will try again

**Comment by waynezw0618** [comment]
Besides, I install everything by Anaconda3, and Now I am running baseline flow solver. seems it can not load something properly 

`(feniceTensor) weis-mbp:baseline_flow weizhang$ python single_runner.py
iUFL can be obtained from https://github.com/MiroK/ufl-interpreter
resume env
--- call init ---
Warning!! The number of jets was not set in the loaded hdf5 file
Warning!! No value for the lift founded
Warning!! No value for the recirculation area founded
Warning!! Number of probes was changed! Probes buffer content reseted
mesh_file = mesh/turek_2d.h5
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
-0.2 0.21
Traceback (most recent call last):
  File "single_runner.py", line 26, in <module>
    environment = resume_env(plot=500, dump=10, single_run=True)
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/env.py", line 181, in resume_env
    simu_name = simu_name)
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../Env2DCylinder.py", line 126, in __init__
    self.start_class(complete_reset=True)
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../Env2DCylinder.py", line 252, in start_class
    self.flow_params, self.geometry_params, self.solver_params)
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../flow_solver.py", line 98, in __init__
    jets = [JetBCValue(radius, width, theta0, Q=0, degree=1) for theta0 in positions]
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../flow_solver.py", line 98, in <listcomp>
    jets = [JetBCValue(radius, width, theta0, Q=0, degree=1) for theta0 in positions]
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../jet_bcs.py", line 35, in __init__
    self.radius = radius
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 438, in __setattr__
    elif name in self._parameters:
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 432, in __getattr__
    return self._parameters[name]
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 432, in __getattr__
    return self._parameters[name]
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 432, in __getattr__
    return self._parameters[name]
  [Previous line repeated 323 more times]
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 429, in __getattr__
    if name == 'user_parameters':
RecursionError: maximum recursion depth exceeded in comparison`

**Comment by waynezw0618** [comment]
For python2.7. there is a bug for import HDF5file from dolfin, 
see[ https://github.com/conda-forge/fenics-feedstock/issues/88], seems only fixed in python3. that is wired.... please let me know what you have done in your side

**Comment by jerabaul29** [comment]
You mean that you are trying to build the docker from scratch yourself, right? Do not do that, Fenics is known (as you discover) to be a hell to build. Start instead from an official Fenics docker image in the RIGHT version, and add the needed packages (Tensorforce, tensorflow, etc) to it:

https://fenicsproject.org/download/

Not sure how / where the old images are available though, but you may either search the internet or ask on the Fenics forum. Remember to use a Fenics docker in the same version as we name in the appendix.

I still think it would be simplest go ditch Mac OS altogether, and use an Ubuntu virtualbox to run singularity, or an Ubuntu dual boot.

**Comment by waynezw0618** [comment]
I actually pulled a docker image of ubuntu and installed Anaconda there.  so that I can follow the official installation instruction of Fenics as docker provide a ubuntu environment for me.the thing is for python2.7, I can only install Fenics 2016.2.0 by Conda with tensorflow=1.8.0 and so as tensorforce=0.4.2. what I am doing is just add python=2.7 tensorflow=1.8.0 to the installation command for Conda like 
`conda  create -n fenicsproject -c conda-forge fenics python=2.7 tensorflow=1.8.0
`
still some  conflicts ... I don't know if there is any patch I have to do.  As someone in conda forge issue says that only fixed in python3. So simultaneously I installed a Fenics=2019 with python=3.67 and tensorflow=1.10.0 by Conda3 then the problem goes to pickle. as it can not read dict_history_parameters.pkl properly.

'
python single_runner.py
iUFL can be obtained from https://github.com/MiroK/ufl-interpreter
resume env
--- call init ---
Warning!! The number of jets was not set in the loaded hdf5 file
Warning!! No value for the lift founded
Warning!! No value for the recirculation area founded
Warning!! Number of probes was changed! Probes buffer content reseted
mesh_file = mesh/turek_2d.h5
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
-0.2 0.21
Traceback (most recent call last):
  File "single_runner.py", line 26, in <module>
    environment = resume_env(plot=500, dump=10, single_run=True)
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/env.py", line 181, in resume_env
    simu_name = simu_name)
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../Env2DCylinder.py", line 126, in __init__
    self.start_class(complete_reset=True)
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../Env2DCylinder.py", line 252, in start_class
    self.flow_params, self.geometry_params, self.solver_params)
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../flow_solver.py", line 98, in __init__
    jets = [JetBCValue(radius, width, theta0, Q=0, degree=1) for theta0 in positions]
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../flow_solver.py", line 98, in <listcomp>
    jets = [JetBCValue(radius, width, theta0, Q=0, degree=1) for theta0 in positions]
  File "/Users/weizhang/software/ML/Cylinder2DFlowControlWithRL3/baseline_flow/../jet_bcs.py", line 35, in __init__
    self.radius = radius
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 438, in __setattr__
    elif name in self._parameters:
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 432, in __getattr__
    return self._parameters[name]
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 432, in __getattr__
    return self._parameters[name]
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 432, in __getattr__
    return self._parameters[name]
  [Previous line repeated 323 more times]
  File "/anaconda2/envs/feniceTensor/lib/python3.6/site-packages/dolfin/function/expression.py", line 429, in __getattr__
    if name == 'user_parameters':
'
Some suggestion?

**Comment by jerabaul29** [comment]
Not really, as I said I recommend that you find the official fenics container in the right version and build further on it by pip install tensorforce etc, or even better that you use a Ubuntu host (from either virtualbox or a dual boot) to run our singularity image.

**Comment by waynezw0618** [comment]
Do I really need some patches?  As I can install Fenics, Tensorflow, tensorforce simutanously 
then I get the errors like :


`-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'craypetsc_real;PETSc'
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of PetscInt
-- Check size of PetscInt - done
-- Checking for one of the modules 'crayslepc_real;SLEPc'
-- Found SWIG: /usr/bin/swig (found version "3.0.12") 
CMake Deprecation Warning at /usr/share/cmake-3.10/Modules/UseSWIG.cmake:231 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  CMakeLists.txt:77 (swig_add_module)


-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    DEBUG


-- Build files have been written to: /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21
/usr/bin/cmake -H/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 -B/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef
60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/CMakeFiles /tmp/tmpLae00b2
019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21'
make -f CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/build.make CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/depend
make[2]: Entering directory '/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21'
[ 33%] Swig source
/usr/bin/cmake -E make_directory /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21
/usr/bin/swig -python -module dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 -shadow -modern -modernargs -fastdispatch -fvirtual -nosafecstrings -noproxydel -fastproxy -fastinit -fastunpack 
-fastquery -nobuildnone -DDOLFIN_VERSION="2017.2.0" -DDOLFIN_LA_INDEX_SIZE=4 -DHAS_SLEPC -DHAS_PETSC -DHAS_PETSC4PY -DHAS_SLEPC4PY -DHAS_MPI -DNUMPY_VERSION_MAJOR=1 -DNUMPY_VERSION_MINOR=13 -
DNUMPY_VERSION_MICRO=3 -DNPY_NO_DEPRECATED_API=NPY_1_13_API_VERSION -c++ -fcompact -O -I. -small -outdir /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_f
d0bfd70e26309e6d4ea98184c161df7264beb21 -c++ -I/usr/include -I/usr/include/eigen3 -I/usr/include/hdf5/openmpi -I/usr/lib/python2.7/dist-packages/petsc4py/include -I/usr/lib/x86_64-linux-gnu/o
penmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022
/libevent/include -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/lib/petscdir/3.7.7/x86_64-linux-gnu-real/include -I/usr/include/hypre -I/usr/include/superlu -I/usr/include/suitesparse -I
/usr/lib/x86_64-linux-gnu/hdf5/openmpi/include -I/usr/include/scotch -I/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264
beb21/. -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/slepc4py/include -I/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a0
2cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 -o /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c1
61df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21PYTHON_wrap.cxx /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161
df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i
/usr/include/dolfin/function/Function.h:65: Warning 402: Base class 'Hierarchical< Function >' is incomplete.
/usr/include/dolfin/swig/function/pre.i:242: Warning 402: Only forward declaration 'Hierarchical< Function >' was found.
/usr/include/dolfin/function/Function.h:66: Warning 520: Derived class 'Function' of 'dolfin::GenericFunction' is not similarly marked as a smart pointer.
/usr/include/dolfin/function/Function.h:66: Warning 520: Derived class 'Function' of 'ufc::function' is not similarly marked as a smart pointer.
/usr/include/dolfin/function/Function.h:66: Warning 520: Derived class 'Function' of 'dolfin::Variable' is not similarly marked as a smart pointer.
/usr/include/dolfin/function/FunctionSpace.h:53: Warning 402: Base class 'Hierarchical< FunctionSpace >' is incomplete.
/usr/include/dolfin/swig/function/pre.i:241: Warning 402: Only forward declaration 'Hierarchical< FunctionSpace >' was found.
/usr/include/dolfin/function/FunctionSpace.h:54: Warning 520: Derived class 'FunctionSpace' of 'dolfin::Variable' is not similarly marked as a smart pointer.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:187: Warning 31
5: Nothing known about 'std::cos'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:188: Warning 31
5: Nothing known about 'std::sin'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:189: Warning 31
5: Nothing known about 'std::tan'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:190: Warning 31
5: Nothing known about 'std::acos'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:191: Warning 31
5: Nothing known about 'std::asin'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:192: Warning 31
5: Nothing known about 'std::atan'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:193: Warning 31
5: Nothing known about 'std::atan2'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:194: Warning 31
5: Nothing known about 'std::cosh'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:195: Warning 31
5: Nothing known about 'std::sinh'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:196: Warning 31
5: Nothing known about 'std::tanh'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:197: Warning 31
5: Nothing known about 'std::exp'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:198: Warning 31
5: Nothing known about 'std::frexp'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:199: Warning 31
5: Nothing known about 'std::ldexp'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:200: Warning 31
5: Nothing known about 'std::log'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:201: Warning 31
5: Nothing known about 'std::log10'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:202: Warning 31
5: Nothing known about 'std::modf'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:203: Warning 31
5: Nothing known about 'std::pow'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:204: Warning 31
5: Nothing known about 'std::sqrt'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:205: Warning 31
5: Nothing known about 'std::ceil'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:206: Warning 31
5: Nothing known about 'std::fabs'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:207: Warning 31
5: Nothing known about 'std::floor'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:208: Warning 31
5: Nothing known about 'std::fmod'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:209: Warning 31
5: Nothing known about 'std::max'.
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.i:210: Warning 31
5: Nothing known about 'std::min'.
cd /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/tmpLa
e00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b99
1c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 /tmp/tmpLae00b
2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 /tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/d
olfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/DependInfo.cmake --color=
Dependee "/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264b
eb21.dir/DependInfo.cmake" is newer than depender "/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/CMakeFiles/_do
lfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/depend.internal".
Dependee "/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/CMakeFiles/CMakeDirectoryInformation.cmake" is newer th
an depender "/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df72
64beb21.dir/depend.internal".
Scanning dependencies of target _dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21
make[2]: Leaving directory '/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21'
make -f CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/build.make CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/build
make[2]: Entering directory '/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21'
[ 66%] Building CXX object CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21PYTHON_wrap.cxx.o
/usr/bin/c++  -DDOLFIN_LA_INDEX_SIZE=4 -DDOLFIN_SIZE_T=8 -DDOLFIN_VERSION=\"2017.2.0\" -DHAS_CHOLMOD -DHAS_HDF5 -DHAS_MPI -DHAS_PETSC -DHAS_PETSC4PY -DHAS_SCOTCH -DHAS_SLEPC -DHAS_SLEPC4PY -D
HAS_UMFPACK -DHAS_ZLIB -DNDEBUG -DNPY_NO_DEPRECATED_API=NPY_1_13_API_VERSION -DNUMPY_VERSION_MAJOR=1 -DNUMPY_VERSION_MICRO=3 -DNUMPY_VERSION_MINOR=13 -D_FORTIFY_SOURCE=2 -D_dolfin_fd0bfd70e26
309e6d4ea98184c161df7264beb21_EXPORTS -isystem /usr/include/eigen3 -isystem /usr/include/hdf5/openmpi -isystem /usr/lib/python2.7/dist-packages/petsc4py/include -isystem /usr/lib/x86_64-linux
-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mc
a/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /usr/lib/petscdir/3.7.7/x86_64-linux-gnu-real/include -isystem /usr/include/hypre -isystem /u
sr/include/superlu -isystem /usr/include/suitesparse -isystem /usr/lib/x86_64-linux-gnu/hdf5/openmpi/include -isystem /usr/include/scotch -I/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02
cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/. -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/
slepc4py/include -I/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21 -isystem /usr/lib/slepcdir/3.7.4/x86_64-linux-
gnu-real/include  -fpermissive   -O2 -fPIC   -std=c++11 -o CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21PYTHON_wrap.cxx.o -c 
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21PYTHON_wrap.cxx
/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21PYTHON_wrap.cxx:32
62:10: fatal error: numpy/arrayobject.h: No such file or directory
 #include <numpy/arrayobject.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/build.make:71: recipe for target 'CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/dolfin_fd0bfd70e26309e6d4ea98
184c161df7264beb21PYTHON_wrap.cxx.o' failed
make[2]: *** [CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21PYTHON_wrap.cxx.o] Error 1
make[2]: Leaving directory '/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/all' failed
make[1]: *** [CMakeFiles/_dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21.dir/all] Error 2
make[1]: Leaving directory '/tmp/tmpLae00b2019-7-3-19-42_instant_1b8825fef60a02cd05a67da64ac1585bbb9b991c/dolfin_fd0bfd70e26309e6d4ea98184c161df7264beb21'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by jerabaul29** [comment]
I am not sure of what you mean. I think you should use the Fenics container as the starting point, so that you do not need to install / compile Fenics yourself.

The other possibility (finding an Ubuntu machine) may be the best.

**Comment by waynezw0618** [comment]
Hi, Now I run base_flow solve in docker container. I will follow your steps to make sure that everything works fine in the container.

**Comment by jerabaul29** [comment]
Sounds good.

- Please confirm me when you can double check that everything is working well.

- You were writing something about a server in your comment before you edited it. Could you for example put the docker image on google drive or similar and share the link? Then I can put it on my webpage, and link to it from the readme giving you credits. How should I give you credit? Would 'Wei Zhang' be enough?

**Comment by waynezw0618** [comment]
- It currently works for all three situations, except runtime visualization. I am checking the problem. and you can find the issue here [https://github.com/matplotlib/matplotlib/issues/14721](url). I want to know if you have problem with it? I will try to figure out that sooner. 

- It is about 3Gb in size. I need to check where I can upload. do you have some private cloud so I can send it to you?

- I am happy if you can put my name there. 

I dropped an email to you, since I am playing with your code with my application. I would like if we can discuss that further in email.

Yours Wei

**Comment by jerabaul29** [comment]
Hi! Sounds good! I am in holidays, I will answer in more details next week! :)

Cheers,

Jean

**Comment by jerabaul29** [comment]
Ok, I looked at the issue, it looks like this is again some strange MacOS / Matplotlib issue, so not much I can do there to help either.

I do not have a server to which I can give you access. Could you try to zip the file to reduce its size a bit? Could you upload it for example to dropbox / google drive / one drive / similar system, and provide me a link with read access? The latest solution for example (one drive) should give you a free 5GB quota.

When I receive the file, I can:

- Copy it to my private university server and give access to this specific file in the same way as with the docker container.

- Put a link, with your name and acknowledgement for you contribution (by the way, how do you want to ve acknowledged? Can you send me the exact text I should use; I guess [name], [family name], [email address], [github username] would be good, but feel free to say what you want.

Does that sound ok?

**Comment by waynezw0618** [comment]
Hi 
That sounds nice to me.  I am seeking somewhere I can upload such a large file, since I cannot access either of them.I will drop you an email to send you my email address and other information.

talk to you soon

**Comment by jerabaul29** [comment]
Excellent. I wait for your email, and once this is ready I will do it.

**Comment by jerabaul29** [comment]
Closing as we have confirmed that it is purely a Mac OS related problem.
